@startuml

title "Rest API"

actor Client as u
participant Controller as c
participant Service as s
participant Repository as r
participant DB as db

u -> c: HTTP request
c -> s: send data to service method
s -> r: call repository method
r -> db: execute query
db -> r: receive data, map to classes
r -> s: return business object
s -> c: return data
c -> u: http response

@enduml